server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
    neo4j:
      uri: http://127.0.0.1:7474
      username:
      password: 



